import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../Components/Navbar";
import Hero from "../Components/Hero";
import Attendance from "../public/assets/Attendance.jpg";
import Onboarding from "../public/assets/Onboarding.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Schoolbus Karo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex">
        <div className="w-2/3 h-screen flex flex-col">
          <Navbar />
          <Hero />
        </div>
        <div className="w-1/3 h-screen [background:linear-gradient(#38B2AC,transparent)] relative">
          <div className="absolute overflow-hidden hero-image right-10 top-10">
            <Image src={Attendance} alt="attendance" />
          </div>
          <div className="absolute overflow-hidden hero-image right-[300px] top-[87px]">
            <Image src={Onboarding} alt="attendance" />
          </div>
        </div>
      </main>
    </div>
  );
}
