import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar'
import Hero from '../Components/Hero'

//& Website Homepage Function
/// This is the Main Landing Page of the Website

export default function Home({ props }) {
  // Better Comments Usage
  //& Important Headings
  //$ Secondary Sections and Headings
  //! Warnings and Todo Markers
  //` Function or Variable Descriptions
  //? Color Option 1
  //@ Color Option 2
  //// Additional Non-Intrusive Comments

  /// Prop Description on a page
  /// props.propName1 = Description 1 (String)
  /// props.propName2 = Description 2 (Boolean)
  /// props.propName3 = Description 3 (URL/File)

  //$ Calculate Heavy Data
  const heavyData = () => {
    try {
      //` Do Something Here
    } catch (error) {
      console.log(error)
    }
  }

  //& View
  return (
    <div>
      {/* //& Website Heading and Meta Data */}
      <Head>
        <title>Schoolbus Karo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex">
        {/* //$ Website Navbar */}
        <div className="w-2/3 h-screen flex flex-col">
          <Navbar />
          <Hero />
        </div>
        {/* //$ Mockup Photo */}
        <div className="w-1/3 h-screen [background:linear-gradient(#38B2AC,transparent)] relative">
          <div className="absolute overflow-hidden hero-image right-10 top-10">
            <Image src={'/assets/Attendance.jpg'} alt="attendance" layout="fill" />
          </div>
          <div className="absolute overflow-hidden hero-image right-[300px] top-[87px]">
            <Image src={'/assets/Onboarding.jpg'} layout="fill" alt="attendance" />
          </div>
        </div>
      </main>
    </div>
  )
}

//! Other Functions or Views Here
